services:
    # APPLICATION MAIN WEB API
    web:
        build: .
        container_name: atomictickets_web
        command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            postgres_db:
                condition: service_healthy
            redis:
                condition: service_started

    # CELERY WORKER
    worker:
        build: .
        container_name: atomictickets_worker
        command: "celery -A src.worker.celery_app worker --loglevel=info"
        env_file:
            - .env
        depends_on:
            redis:
                condition: service_started
            postgres_db:
                condition: service_healthy

    # DATABASE
    postgres_db:
        image: postgres:16
        container_name: atomictickets_db
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
                ]
            interval: 5s
            retries: 5

    # 4. BROKER/CACHE
    redis:
        image: redis:7-alpine
        container_name: atomictickets_redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        restart: unless-stopped
        command: redis-server --appendonly yes

volumes:
    pg_data:
    redis_data:
